import { PropType } from "@/util/Types";
import Head from "next/head";
import Header from "./Header";

export default function Layout({ children }: PropType): JSX.Element {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, inital-scale=1" />
        <link rel="icon" href="./" />
      </Head>
      <Header />
      <main className="container m-auto mx-xl">{children}</main>
    </>
  );
}
